apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: spring-oauth2-service
  labels:
    app: spring-oauth2
spec:
  type: NodePort
  selector:
    app: spring-oauth2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
