#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - virtualbox
  - virtualbox-ext-pack
runcmd:
  - wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - chmod +x minikube-linux-amd64
  - sudo mv minikube-linux-amd64 /usr/local/bin/minikube