on: push
name: pipeline deploy
jobs:
  pipeline:
    name: despliegue a cluster
    runs-on: ubuntu-20.04
    steps:
      - name: bajar codigo al servidor
        uses: actions/checkout@master
      - name: construir y subir a dockerhub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
      - name: use Deployment if not exists
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: kubectl get deployment spring-oauth2-deployment | tail -n +2 && kubectl apply -f Deployment.yaml
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployment/spring-oauth2-deployment container=${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/spring-oauth2-deployment"'
